# Generated by Django 5.2 on 2025-07-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('question', models.TextField(max_length=400)),
                ('answer', models.TextField(max_length=300)),
                ('priority', models.CharField(choices=[('L', 'low'), ('M', 'medium'), ('H', 'high')], max_length=1)),
            ],
            options={
                'verbose_name': 'The Question, The Answer',
                'verbose_name_plural': 'User Questions, User Answers',
            },
        ),
    ]
